analysis_test_mc:
  stage: analysis
  extends:
    - .base_analysis
  script:
    - echo "Running bbww analysis in barista framework"
    - source bbreww/scripts/analysis_test_mc.sh --output-base /builds/$CI_PROJECT_PATH/output/
  artifacts:
    paths:
      - output/analysis_test_mc/test.coffea
    expire_in: 1 day

analysis_test_data:
  stage: analysis
  extends:
    - .base_analysis
  script:
    - echo "Running bbww analysis (with data) in barista framework"
    - source bbreww/scripts/analysis_test_data.sh --output-base /builds/$CI_PROJECT_PATH/output/
  artifacts:
    paths:
      - output/analysis_test_data/test.coffea
    expire_in: 1 day

skimmer_analysis_test:
  stage: analysis
  extends:
    - .base_analysis
  needs:
    - setup_workspace
    - voms_proxy
    - skimmer_test
  script:
    - echo "Running bbww skimmer analysis in barista framework"
    - source bbreww/scripts/skimmer_analysis_test.sh --output-base /builds/$CI_PROJECT_PATH/output/
  artifacts:
    paths:
      - output/skimmer_analysis_test/test.coffea
    expire_in: 1 day


analysis_plot_mc:
  stage: plot
  extends:
    - .base_analysis
  needs:
    - setup_workspace
    - analysis_test_mc
    - voms_proxy

  script:
    - echo "Running bbww plot_mc analysis in barista framework"
    - source bbreww/scripts/analysis_plot_mc.sh
  artifacts:
    paths:
      - output/analysis_plot_mc/
    expire_in: 1 day
