analysis_test_mc:
  stage: analysis
  extends:
    - .base_bbww_job
  script:
    - echo "Running bbww analysis in barista framework"
    - source bbreww/scripts/analysis_test_mc.sh --output-base $CI_PROJECT_PATH/output/
  artifacts:
    paths:
      - output/analysis_test_mc/test.coffea
    expire_in: 1 day

analysis_test_data:
  stage: analysis
  extends:
    - .base_bbww_job
  script:
    - echo "Running bbww analysis (with data) in barista framework"
    - source bbreww/scripts/analysis_test_data.sh --output-base $CI_PROJECT_PATH/output/
  artifacts:
    paths:
      - output/analysis_test_data/test.coffea
    expire_in: 1 day

skimmer_analysis_test:
  stage: analysis
  extends:
    - .base_bbww_job
  needs:
    - setup_workspace
    - voms_proxy
    - skimmer_test
  script:
    - echo "Running bbww skimmer analysis in barista framework"
    - source bbreww/scripts/skimmer_analysis_test.sh --output-base $CI_PROJECT_PATH/output/
  artifacts:
    paths:
      - output/skimmer_analysis_test/test.coffea
    expire_in: 1 day