analysis_test_run3:
  stage: analysis
  extends:
    - .base_bbww_job
  image: gitlab-registry.cern.ch/cms-cmu/coffea4bees:latest
  script:
    - echo "Running bbww analysis in coffea4bees framework"
    - source bbww/scripts/analysis_test_run3.sh --output-base output/
  artifacts:
    paths:
      - coffea4bees_framework/output/analysis_test_run3/
    expire_in: 1 day

analysis_test_data_run3:
  stage: analysis
  extends:
    - .base_bbww_job
  image: gitlab-registry.cern.ch/cms-cmu/coffea4bees:latest
  script:
    - echo "Running bbww analysis (with data) in coffea4bees framework"
    - source bbww/scripts/analysis_test_data.sh --output-base output/
  artifacts:
    paths:
      - coffea4bees_framework/output/analysis_test_run3/
    expire_in: 1 day