analysis_test_mc:
  stage: analysis
  extends:
    - .base_bbww_job
  image: gitlab-registry.cern.ch/cms-cmu/coffea4bees:latest
  script:
    - echo "Running bbww analysis in coffea4bees framework"
    - source bbww/scripts/analysis_test_mc.sh --output-base output/
  artifacts:
    paths:
      - coffea4bees_framework/output/analysis_test_mc/test.coffea
    expire_in: 1 day

analysis_test_data:
  stage: analysis
  extends:
    - .base_bbww_job
  image: gitlab-registry.cern.ch/cms-cmu/coffea4bees:latest
  script:
    - echo "Running bbww analysis (with data) in coffea4bees framework"
    - source bbww/scripts/analysis_test_data.sh --output-base output/
  artifacts:
    paths:
      - coffea4bees_framework/output/analysis_test_data/test.coffea
    expire_in: 1 day

skimmer_analysis_test:
  stage: analysis
  needs: skimmer_test
  extends:
    - .base_bbww_job
  image: gitlab-registry.cern.ch/cms-cmu/coffea4bees:latest
  script:
    - echo "Running bbww skimmer analysis in coffea4bees framework"
    - source bbww/scripts/skimmer_analysis_test.sh --output-base output/
  artifacts:
    paths:
      - coffea4bees_framework/output/skimmer_analysis_test/test.coffea
    expire_in: 1 day