analysis_test:
  stage: analysis
  extends:
    - .base_bbww_job
  image: gitlab-registry.cern.ch/cms-cmu/coffea4bees:latest
  script:
    - echo "Running bbww analysis in coffea4bees framework"
    - source bbww/scripts/analysis_test.sh --output-base output/
  artifacts:
    paths:
      - coffea4bees_framework/python/output/analysis_test/
    expire_in: 1 day