analysis_test:
  stage: analysis
  extends:
    - .base_bbww_job
  image: gitlab-registry.cern.ch/cms-cmu/coffea4bees:latest
  script:
    - echo "Running bbww analysis in coffea4bees framework"
    - cd bbww
    # Your bbww analysis commands here
    - source scripts/run_analysis.sh output/
  artifacts:
    paths:
      - coffea4bees_framework/python/bbww/output/
    expire_in: 1 day