analysis_test_cutflows_mc:
  stage: test
  extends:
    - .base_bbww_job
  needs:
    - setup_workspace
    - analysis_test_mc
    - voms_proxy
  image: gitlab-registry.cern.ch/cms-cmu/coffea4bees:latest
  script:
    - echo "Running cutflow test for analysis_test"
    - source bbww/scripts/analysis_test_cutflows_mc.sh --output-base output/
  artifacts:
    paths:
      - coffea4bees_framework/output/analysis_test_cutflows_mc/test_cutflow.yml
    expire_in: 1 day

analysis_test_cutflows_data:
  stage: test
  extends:
    - .base_bbww_job
  needs:
    - setup_workspace
    - analysis_test_data
    - voms_proxy
  image: gitlab-registry.cern.ch/cms-cmu/coffea4bees:latest
  script:
    - echo "Running cutflow test for analysis_test"
    - source bbww/scripts/analysis_test_cutflows_data.sh --output-base output/
  artifacts:
    paths:
      - coffea4bees_framework/output/analysis_test_cutflows_data/test_cutflow_data.yml
    expire_in: 1 day

skimmer_analysis_test_cutflows:
  stage: test
  extends:
    - .base_bbww_job
  needs:
    - setup_workspace
    - analysis_test_data_run3
    - voms_proxy
  image: gitlab-registry.cern.ch/cms-cmu/coffea4bees:latest
  script:
    - echo "Running cutflow test for skimmer_analysis_test"
    - source bbww/scripts/skimmer_analysis_test_cutflows.sh --output-base output/
  artifacts:
    paths:
      - coffea4bees_framework/output/skimmer_analysis_test_cutflows/test_cutflow.yml
    expire_in: 1 day