analysis_test_cutflows:
  stage: test
  extends:
    - .base_bbww_job
  needs:
    - setup_workspace
    - voms_proxy
    - analysis_test
  image: gitlab-registry.cern.ch/cms-cmu/coffea4bees:latest
  script:
    - echo "Running cutflow test for analysis_test"
    - source bbww/scripts/analysis_test_cutflows.sh --base-output output/
  artifacts:
    paths:
      - coffea4bees_framework/python/output/analysis_test_cutflows/
    expire_in: 1 day

analysis_test_cutflows_run3:
  stage: test
  extends:
    - .base_bbww_job
  needs:
    - setup_workspace
    - voms_proxy
    - analysis_test_run3
  image: gitlab-registry.cern.ch/cms-cmu/coffea4bees:latest
  script:
    - echo "Running cutflow test for analysis_test"
    - source bbww/scripts/analysis_test_cutflows_run3.sh output/
  artifacts:
    paths:
      - coffea4bees_framework/python/output/analysis_test_cutflows_run3/
    expire_in: 1 day

skimmer_analysis_test_cutflows:
  stage: test
  extends:
    - .base_bbww_job
  needs:
    - setup_workspace
    - voms_proxy
    - skimmer_analysis_test
  image: gitlab-registry.cern.ch/cms-cmu/coffea4bees:latest
  script:
    - echo "Running cutflow test for skimmer_analysis_test"
    - source bbww/scripts/skimmer_analysis_test_cutflows.sh --base-output output/
  artifacts:
    paths:
      - coffea4bees_framework/python/output/skimmer_analysis_test_cutflows/
    expire_in: 1 day