analysis_plot_mc_bbreww:
  stage: plot
  extends:
    - .base_analysis
  needs:
    - setup_workspace
    - analysis_test_mc_bbreww
    - voms_proxy

  script:
    - echo "Running bbww plot_mc analysis in barista framework"
    - source bbreww/scripts/analysis_plot_mc.sh --output-base /builds/$CI_PROJECT_PATH/output/
  artifacts:
    paths:
      - output/analysis_plot_mc/test_plots_from_yaml/Run3/nominal_4j2b/flavor_sum/region_sum/Hbb_mass.pdf
    expire_in: 1 day

analysis_iplot_mc_bbreww:
  stage: plot
  extends:
    - .base_analysis
  needs:
    - setup_workspace
    - analysis_test_mc_bbreww
    - voms_proxy

  script:
    - echo "Running bbww plot_mc analysis in barista framework"
    - source bbreww/scripts/analysis_iplot_mc.sh --output-base /builds/$CI_PROJECT_PATH/output/
