setting:
  - module: ml.DataLoader
    option:
      - batch_skim: 32768 # 2**15
      - batch_eval: 4194304 # 2**22
      - optimize_sliceable_dataset: true
  - module: ROOT
    option:
      - friend_allow_missing: false
  ## remove the whole block below if you want to use all years ##
  - module: cms.CollisionData
    option:
      - eras:
          2022_preEE: [C, D]
          2022_EE: [E, F, G]
          2023_preBPix: [A, B, C, D]
          2023_BPix: [D, E]
  - module: bbWW.InputBranch
    option:
      - feature_ancillary: ["HT", "njets", "nsoftjets", "year"]
      # remove the "year" from the input when the dataset only contains one year
      # otherwise the variance will be infinite and the output will be NaN
  ##########################################################
