setting:
  - module: ml.DataLoader
    option:
      #- num_workers: 4
      - batch_skim: 393216 # 3 * 2^17
      - batch_eval: 131072 # 2^17
      - optimize_sliceable_dataset: true
  - module: ROOT
    option:
      - friend_allow_missing: false
  ## remove the whole block below if you want to use all years ##
  - module: cms.CollisionData
    option:
      - eras:
          2022_preEE: [C, D]
          2022_EE: [E, F, G]
          2023_preBPix: [C01, C01, C03, C04, C11, C12, C13, C14]
          2023_BPix: [D01, D02, D11, D12]
  - module: bbWW.InputBranch
    option:
      - feature_ancillary: ["njets", "nsoftjets", "HT", "year"]
      # remove the "year" from the input when the dataset only contains one year
      # otherwise the variance will be infinite and the output will be NaN
  ##########################################################
